### ISSUE TITLE
add a little option to enable debug tracing of all jolokia requests executed on the JVM and the amount of time they take?

### ISSUE THREAD

**Issue by jstrachan** [rhuss/jolokia#113]
We've had reports of some functions using up lots of CPU on the JVM side:
https://github.com/hawtio/hawtio/issues/443#issuecomment-21930312

I can imagine as more and more folks use jolokia for all kinds of things (e.g. we're switching Fuse IDE to use it too, maybe JBDS might start, then there's other tools...) I can imagine folks wanting to enable logging to see what requests are being performed on a JVM and how long they all took; to help diagnose CPU usage (which could be excessive polling in some tool).

I wonder if we should add a little option (configurable ideally from JMX but worst case system properties maybe; or if logging is enable for a certain category or something?) that we just dump each JMX operation & MBean name & parameters being evaluated and ideally how many millis they took; so from a quick noodle of the log we could easily detect broken or inefficient tools ;) or find methods that take up lots of time so could be cached or invoked less frequently etc?

**Comment by rhuss** [comment]
Maybe we can even combine that with (self-) health checks, when we have the health checks from rhuss/jolokia-extra#1 in place ? So that if a certain threshold for the execution time of a Jolokia operation is exceeded then a hc fails ? Thinks this is even better than logging because for logging you still have to monitor stuff.

Finally the health checks combined with the new notification support where a health checks fires a JMX notification in case of an incident could be quite powerful for e.g. sending out notifications (for this a 'webhook' like notification backend must exist which is active even when there is no client connected).

If you don't mind, I'll close that one and move the idea to the health check stuff.
