### ISSUE TITLE
Failed to find Premain-Class manifest attribute

### ISSUE THREAD

**Issue by buzdin** [rhuss/jolokia#128]
There is no Premain-Class in jolokia-jvm MANIFEST.MF jar in published maven artifact.
Checked on all published releases on Maven Central.
Also tried to build it, but manifest entries are not populated.

**Comment by jkutner** [comment]
Yea, this is really difficult without docs. @rhuss can you point me to the source for the docs for this page: https://jolokia.org/reference/html/agents.html

I'll be happy to submit a PR with some of this.

For maven, you need:

```xml
<groupId>org.jolokia</groupId>
<artifactId>jolokia-jvm</artifactId>
<version>1.3.1</version>
<classifier>agent</classifier>
```

**Comment by rhuss** [comment]
The jvm agent documentation can be found here: https://github.com/rhuss/jolokia/blob/master/src/docbkx/agents/jvm.xml

However, the agent itself is seldomly used as a Maven dependency, that's also because there is no example in this section with Maven.

What's you use case for using it as Maven dependency ? From the download page you should be able to dowload the proper agent as well when using the distribution package with all agent or when you are using the [jolokia](http://search.cpan.org/~roland/jmx4perl-1.11/scripts/jolokia) cli for on demand downloading.

**Comment by jkutner** [comment]
I'm doing the following so that the download and versioning is part of my build rather than an external dependency:

```xml
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-dependency-plugin</artifactId>
        <version>2.3</version>
        <executions>
            <id>copy-jokolia</id>
            <phase>package</phase>
            <goals><goal>copy</goal></goals>
            <configuration>
              <artifactItems>
                <artifactItem>
                  <groupId>org.jolokia</groupId>
                  <artifactId>jolokia-jvm</artifactId>
                  <version>1.3.1</version>
                  <classifier>agent</classifier>
                  <destFileName>jolokia-agent.jar</destFileName>
                </artifactItem>
              </artifactItems>
            </configuration>
          </execution>
        </executions>
      </plugin>
    </plugins>
  </build>
```
