### ISSUE TITLE
provide a way to specify health checks / availability checks / happy page checks to a JVM with jolokia?

### ISSUE THREAD

**Issue by jstrachan** [rhuss/jolokia#162]
So whenever possible I include jolokia in all JVMs (and docker images with JVMs inside) as a standard REST way to do monitoring and to use the nice hawtio console etc. (I tend to use the java agent approach to avoid modifying the classpath or container in any way)

It'd be awesome if we could auto-generate or manually specify health checks or 'availability checks' that the jolokia agent could use. e.g. that when a JVM is running that certain MBeans should exist; or that certain mbeans should have certain attribute values. Am thinking something along the lines of we can configure the jolokia agent to point at a folder which contains a bunch of, say, json files which contain 'health checks / availability checks'.

Then if this enabled, jolokia would add some API to do the checks. (It could just be a jolokia mbean that gets enabled really - so we use the standard jolokia API to query the health check / availability checks).

e.g. if using Apache Camel; we could auto-generate or manually define that an mbean should exist for a CamelContext along with, say, 3 routes. Then if the JVM / docker image starts, we can have jolokia automatically reply with details of whether its running correctly (and giving details of the failures in JSON if the camel context is not present).

Right now there's no easy way to check jolokia for 'is my stuff really running correctly right now'. By letting folks specify these checks in JMX - as mostly static JSON files - it'd add huge value IMHO.

If folks need really complex health / availability checks - e.g. using dynamic java code and stuff - folks could just implement those as a simple JMX MBean which is then statically referred to in a JSON file for jolokia to query?

i.e. if we just come up with a simple file format for validation checks using (e.g. JSON) we should be able to support most things.

e.g. to verify that a tomcat container starts up and the welcome pages for each WAR can return 200-299 return value.

Users might want to specify known local URL paths within their web apps that should return OK values. (If they return a non OK value we could return the output in the JSON). Then folks could write their own 'happy pages' in servlets / JSP / JAXRS and we can easily invoke them from jolokia.

**Comment by rhuss** [comment]
Sorry, for the long long delay (there was simply to much around it). And yes, I should not give promises on things which I then forget ;-{

I  really can see the value for this. IMO it boils down to two parts: Allowing the agent to be extended in a controlled manner and to provide the health checks.

#### Extending the agent

Jolokia 2.0 already has quite sophisticated hooks for so called *services* which can be provided by various means (classpath lookup for the JVM and WAR agents, OSGi Service lookup for the OSGi agent). There are different types of services which already available. A broad overview can be found on the Jolokia [Wiki](https://github.com/rhuss/jolokia/wiki/Jolokia-Services) (although the actual implementation is a bit different).

But this probably doesn't help much here, because 2.0 is not really ready for prime time and although I have some ideas about the release roadmap, but I can't promise anything since actually there is no really pressure for doing it (at least nobody asked for it yet ;-).

But the good thing is that there is some 'lightweight' service framework also integrated in Jolokia 1.x: [ServiceObjectFactory](https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/util/ServiceObjectFactory.java). It is currently used for server detectors and simplifiers (for serialization to JSON). My suggestion is to introduce a lifecycle service which is started in a similar way. That way anything could be started during the startup of the agent. This will work for the WAR and JVM agent. For the OSGi stuff a dedicated ServiceTracker could be added for this purpose.

#### Health Checks

Given that this startup service hook is in place, one could then easily provide a custom service which registers an own MBean for doing the health check. This MBean could be implemented in any way. The only open task is how and in which form this MBean can get access to the JMX. This could be either by providing directly the MBeanServers detected by the agent so the health checks can do JMX call on its own. This would be the simplest and probably best way. 

And alternative to provide access to the JSON parsing layer so that JMX calls could be done like other Jolokia clients. This would probably be easier for implementer of such services, but would be not as performant as direct JMX access.

----- 

My overall suggestion is to tackle the two task separately: I'm going to implement the lifecycle-service hook directly within Jolokia (and available in the next Jolokia release). Then, you could implement this service API and provide an implementation for an HealthCheck the way you like. For providing an appropriate packaged agent, I would suggest to use [jolokia-extra](https://github.com/rhuss/jolokia-extra) where I already have a customized agent for JSR-77 deserialization on WebSphere. 

----- 

What do you think ?

**Comment by jstrachan** [comment]
That all sounds good. 

I made a little experiment defining a few kinds of assertion we could use
https://github.com/jstrachan/jolokia/tree/liveness/agent/core/src/main/java/org/jolokia/health

e.g. SearchAssertion does a search and asserts the count of mbeans returned; then ReadAssertion makes an assertion on an mbean attribute value.

Here's a few test cases that show them in action:
https://github.com/jstrachan/jolokia/tree/liveness/agent/core/src/test/java/org/jolokia/health

e.g. typical output after simulating some failures is:
```
Results: [Failure{assertion=ReadAssertion{id=my.check, description=Check that the cpu load is valid, mbeanName='java.lang:type=OperatingSystem', attribute='ProcessCpuLoad', comparison='<', value=-1000}, actualValue=0.0}]
Results: [Failure{assertion=SearchAssertion{id=my.check, description=Check that we have enough cheese beans, mbeanName='foo.cheese:type=*', comparison='>', count=1}, actualValue=0}]
```
i.e. its clear from the results which assertions failed.

We could then have an mbean that lets folks pass in JSON for assertions to perform ad hoc assertion checks.

I was hoping we could then have support for a folder of files which are each json and can load one or more assertions; evaluate them all and return the failures if there are any. Then if we get that far, we could add some REST API in jolokia for the health check; returning OK if there are no failures; if there are failures it'd be nice to return the JSON of the failures.

**Comment by rhuss** [comment]
Looks good, my suggestion is:

* To move the checking code rhuss/jolokia-extra which also will use the new, yet-to-come `CustomizeService` for registering one or more MBeans
* One for doing ad-hoc checks by uploading JSON formatted assertions.
* And one for using predefined checks, e.g. by looking into a folder or lookup from the classpath. For specifying a folder I will add a way for the `CustomizeService`s to access the configuration information (which then can be used to specify the server side folder). That way we could avoid to extend the Jolokia protocol since we could simply use an EXEC request for accessing the MBean which uses the preconfigured checks.

I will now focus on the customizer service so that in the next step we can hook in the health checks.

**Comment by nevenr** [comment]
Hi,

I already had some thoughts about jolokia and application health checks / monitoring and I figured it out that it would be nice to have some features listed below.

For the sake of simplicity I will try to explain it on real world use case: check if used memory is less or equal to 80% maximum allowed.

We need to:
* define what data should be considered
	* read mbean attribute / exec mbean operation
	* example:
		* read / java.lang:type=Memory / HeapMemoryUsage
* query (filter) necessary info from complex output structure
	* optimization, we can use "path" but in that case we need to perform multiple reading/executing
	* example:
		* usedVar = aboveRead.used
		* maxVar = aboveRead.max
* manipulate with values
	* example:
		* 80PctMaxVar = 0.8 * maxVar
* compare values (check criteria)
	* example:
		* usedVar > 80PctMaxVar
* optional blocks
	* support for different process state (e.g. on web container if application is deployed we should perform some checks, otherwise not)

Here is example of ad-hoc JSON formatted assertions:
```json
{
  "dataCollection": [
    {
      "id": "first",
      "cmd": "read",
      "mbean": "java.lang:type=Memory",
      "attribute": "HeapMemoryUsage"
    },
    {
      "id": "second",
      "cmd": "exec",
      "mbean": "com.mycompany:type=Something",
      "operation": "someOperation"
    }
  ],
  "vars": [
    {"usedVar": "first.used"},  // additional filtering
    {"maxVar": "first.max"},
    {"80PctMaxVar": "0.8 * maxVar"} // values manipulation
  ],
  "assertions": [
    {
      "id": "request_123",
      "check": "usedVar > 80PctMaxVar",
      "desc": " ... message ..."
    }
  ],
  "conditionalBlocks": [
    {
      "condition": "second.something != 0",
      "dataCollection": [],
      "vars": [],
      "assertions": [],
      "conditionalBlocks": []
    }
  ]
}

```

What do you guys think ?

Regards,
N.

**Comment by rhuss** [comment]
Having a DSL for specifying health-checks (aka monitoring) is a good thing. However, I wouldn't do it in JSON but probably with something more expressive like Groovy, since this is already a language. 

Also, as stated above, this is to much for the vanilla agent. I already included some hooks for custom plugins which could implement this kind of health checks via own MBeans which then communicate over the normal Jolokia protocol (probaly EXEC). 

I will soon have a POC based on @jstrachan suggestion in `jolokia-extra`. Please stay tuned ....

**Comment by rhuss** [comment]
A proof-of-concept is now available at [jolokia-extra](https://github.com/rhuss/jolokia-extra). You can build the agent with @jstrachan 's sample test health checks included on you own (`mvn -Phealth clean install` which creates the JVM and WAR agent below `agents/`) or you can download them as Snapshots([JVM](https://oss.sonatype.org/content/repositories/snapshots/org/jolokia/extra/jolokia-extra-jvm/1.3.0-SNAPSHOT/jolokia-extra-jvm-1.3.0-20150117.074012-1.jar) or [WAR](https://oss.sonatype.org/content/repositories/snapshots/org/jolokia/extra/jolokia-extra-war/1.3.0-SNAPSHOT/jolokia-extra-war-1.3.0-20150117.074000-3-health.war) agent).

If used as usual, it will install a MBean **jolokia:type=plugin,name=health** with two operations:

* `cpuLoadCheck` : to be called with a single int-argument, which specifies the alarming threshold. If the CPU load is below this value, an `code` null string is returned, otherwise an error description.
* `mbeanCountCheck` : Simple, dump check which only checks whether the there are any MBeans matching the pattern `java:lang=*`

Of course this is only a beginning, but show nicely how to hook into Jolokia: Via a plugin which is called during startup, getting a `MBeanPluginContext` which can be used to register a MBean (which automatically get unregistered when the agent goes down) and also for accessing the local MBeanServers (which can be many) in order to perform the health checks. The communication the simply uses the current Jolokia protocol, which is IMO a good thing (as an alternative to introducing a new command `health`).

Next steps will happen on *jolokia-extra*. I will open an issue there collecting all ideas we have so far so that we can implement a feature rich, flexible health check system.

**Comment by rhuss** [comment]
A POC is done in jolokia-extra,  a [blog post](https://ro14nd.de/Health-Checks/) is written and I suggest to continue the discussion for the healthcheck implementation in issue rhuss/jolokia-extra#1

I'll add some backlinks in this new issue and will close that one.
