### ISSUE TITLE
jolokia在aix平台下无法访问

### ISSUE THREAD

**Issue by a1721615168** [rhuss/jolokia#175]
通过内嵌模式启动，然后通过netstat -an|grep 9999 可以看到9999端口已经起开了，
然后通过http://localhost:9999/jmx/...去访问 一直都没有返回结果。

**Comment by rhuss** [comment]
sorry, please reopen in english

**Comment by a1721615168** [comment]
i use jolokia to convert jmx to http, windows or other operation system can normal visit,
but when i use it on ibm aix operation system,it don't work, see the 9999 port is initiated by command me,

http://localhost:9999/jmx/... it don't return a response.

**Comment by rhuss** [comment]
Which agent did you use and how did you start it ? AIX is an Operating System, not an Java application. Which JVM are you using ? 

Since I think it's more about the setup of Jolokia I suggest to come over to the [Jolokia Forum](http://www.jolokia.org/forum.html) where this sort of problems are discussed.
