### ISSUE TITLE
JVM Agent not compatible with -XX:+PerfDisableSharedMem

### ISSUE THREAD

**Issue by thobbs** [rhuss/jolokia#198]
For some reason, the Jolokia agent does not appear to be compatible with the ``-XX:+PerfDisableSharedMem`` JVM option.

I'm testing this against Cassandra.  When running with the option:
~~~bash
$ java -jar ~/Downloads/jolokia-jvm-1.3.0-agent.jar list
6826   /home/thobbs/Downloads/jolokia-jvm-1.3.0-agent.jar list
~~~

And when running without the option (no other changes):
~~~bash
$ java -jar ~/Downloads/jolokia-jvm-1.3.0-agent.jar list
7108   /home/thobbs/Downloads/jolokia-jvm-1.3.0-agent.jar list
6917   org.apache.cassandra.service.CassandraDaemon
~~~

Although I don't think it makes a difference, this is my Java version:

~~~
java version "1.8.0_45"
Java(TM) SE Runtime Environment (build 1.8.0_45-b14)
Java HotSpot(TM) 64-Bit Server VM (build 25.45-b02, mixed mode)
~~~

**Comment by rhuss** [comment]
The "list" command can only show the processes which comes out of `com.sun.tools.attach.VirtualMachine.list()` (see [here](https://github.com/rhuss/jolokia/blob/master/agent/jvm/src/main/java/org/jolokia/jvmagent/client/util/VirtualMachineHandler.java#L107) how it is used in Jolokia).

It seems that adding the parameter will prevents the JVM to be included.

What you still try is to find out the process id and connect directly to the process with `java -jar jolokia.jar <pid>`. I guess, an error will occur but would be curious what kind of error ;-)

**Comment by rhuss** [comment]
I'm afraid that I can't do much here from Jolokia's side. Its more a bug of the JVM, but since I'm using some 'non-official' API (in the `com.sun` namespace) I'm afraid that Oracle won't fix this, too. But would be worth a try.

And thanks for finding out, btw ;-)

**Comment by thobbs** [comment]
I was afraid that might be the answer.  Thank you for taking the time to look into it anyway!

As you guessed, an error does occur if you try to connect to the process anyway:

~~~bash
$ java -jar jolokia-jvm-1.3.0-agent.jar list
29274   jolokia-jvm-1.3.0-agent.jar list
$ pgrep -f CassandraDaemon
29040
$ java -jar jolokia-jvm-1.3.0-agent.jar start 29040 --verbose
Illegal Argument (command: start) : Cannot attach to process-ID 29040.
See --help for possible reasons.
java.lang.IllegalArgumentException: Cannot attach to process-ID 29040.
See --help for possible reasons.
	at org.jolokia.jvmagent.client.util.VirtualMachineHandler.getProcessId(VirtualMachineHandler.java:171)
	at org.jolokia.jvmagent.client.util.VirtualMachineHandler.attachVirtualMachine(VirtualMachineHandler.java:66)
	at org.jolokia.jvmagent.client.AgentLauncher.main(AgentLauncher.java:57)
~~~

**Comment by rhuss** [comment]
Sorry for that ;-(. Some last note, which often gets overseen: You need to run under the **exact** same UID as the JVM process is running with. Strangely, it is not enough to call this under UID 0. This is probably not the case here, just want to mention it ;-)

**Comment by jhermann** [comment]
BTW, the UID restriction got introduced not too long ago with updates of Java8 (I think 8u11 still worked with UID 0, and 8u40 definitely doesn't anymore).

**Comment by rhuss** [comment]
I have the UID also for Java 7 (however don't know exactly at which version).

**Comment by skeyl** [comment]
Just want to say this thread really helped me out a lot. Thanks guys.

**Comment by apoorv007** [comment]
I wonder why is the agent not able to connect when directly given a PID. This seems like an issue on agent rather than JVM, since a JMX client like JConsole is able to connect when directly given a PID.

I believe that `-XX:+PerfDisableSharedMem` option only hampers the discovery of available java processes. I see that in both cases (i.e when PID is given OR when process name regex is given), `VirtualMachineHandler.listProcesses()` is invoked. Shouldn't the agent just try to connect when given a PID? Please let me know if I am missing out something.

Thanks

**Comment by rhuss** [comment]
Actually, you are right, since the agent doesn't even try to attach to the PID if it is not listable, in order to give a meaningful error description.  See here where this check happens: https://github.com/rhuss/jolokia/blob/95f928f084f60ad67738c37ab4368cd82ec2bae9/agent/jvm/src/main/java/org/jolokia/jvmagent/client/util/VirtualMachineHandler.java#L182-L182

This was also because I (falsely ?) assumed that every process which can be attached to is also listed. 

I can move this check up and try nevertheless. Thanks for spotting this.

**Comment by apoorv007** [comment]
Thanks for the quick fix. When will 1.3.7 get released?

**Comment by rhuss** [comment]
There's no schedule yet, but I hope until this end of this month.
