### ISSUE TITLE
Disable authentication for certain endpoints

### ISSUE THREAD

**Issue by pulse00** [rhuss/jolokia#210]
We're exposing spring health checks through jolokia and would like to turn authentication off only for this specific endpoint.

Is it currently possible to have a more granular control over what is protected by basic auth, so we can disable auth for this endpoint only?

**Comment by rhuss** [comment]
This really depends on how the agent is embedded in your system, since Jolokia relays authentication mostly to the runtime container (e.g. servlet authentication when running as WAR agent). It's only the JVM agent which does authentication on its own.

You probably want some control for *authorization*. This can be achieved by providing a poilicy file as described in the [manual](https://jolokia.org/reference/html/security.html) and which allows fine grained control for what is accessible with Jolokia and what not.

In Jolokia 2.0 this concept will be extended to support role based authorization, too.

Does this help you ?

**Comment by pulse00** [comment]
yes, thanks a lot.
