### ISSUE TITLE
No Servlet Container Info from jolokia info 

### ISSUE THREAD

**Issue by lgbff** [rhuss/jolokia#251]
I try the follow uri:
wget http://localhost:80/jolokia/
response:
```
{"timestamp":1458205346,"status":200,"request":{"type":"version"},"value":{"protocol":"7.2","config":{"detectorOptions":"{}","canonicalNaming":"true","maxCollectionSize":"0","includeStackTrace":"true","historyMaxEntries":"10","agentId":"1.1.1.1-6044-1526c3d4-servlet","debug":"false","dispatcherClasses":"org.jolokia.jsr160.Jsr160RequestDispatcher","maxDepth":"15","maxObjects":"0","discoveryEnabled":"false","serializeException":"false","agentType":"servlet","debugMaxEntries":"100"},"agent":"1.3.3","info":{}}}
```
The info block is empty, why?
Is the a tomcat settings problem?

**Comment by luettenberg** [comment]
Hello,

got the same issue. 

Environment:
* Debian 8.4 Jessie
* Tomcat 8.0.14 (installed via apt)
* Jolokia 1.3.3 deployed as war-File

The Problem seems to be the pattern in Class jolokia/agent/core/src/main/java/org/jolokia/detector/TomcatDetector.java. This Class evaluates the attribute serverInfo. 

In my case serverInfo is set to : "Apache Tomcat/8.0.14 (Debian)"
The Pattern "^\\s*([^/]+)\\s*/\\s*([\\d\\.]+(-RC\\d+)?)" found in TomcatDetector does not match so it returns null.

A fix would be nice because mk_jolokia script from check_mk evaluates productinformation and does container dependend checks if set. 

Thanks for your help

**Comment by luettenberg** [comment]
Assigned a Pull-Request with changed Regex for this issue.

**Comment by rhuss** [comment]
Sorry, I was too fast (thats not often the case ;-) Thanks for the PR, I'm just pushing a snapshot.

@lgbff what Tomcat are you using ?

**Comment by rhuss** [comment]
tbh, I don't know when I'm going to release 1.3.4, hopefully soon but I don't have much 'material' yet for it.

**Comment by luettenberg** [comment]
Thanks for the quick fix. Deleted PR. The release is no problem for me - latest snapshot is all i need.

**Comment by luettenberg** [comment]
Quickfix for those who cannot wait until release of 1.3.4:

1. Create File CATALINA_BASE/lib/org/apache/catalina/util/ServerInfo.properties with Content:
`server.info=Apache Tomcat/8.0.14`
2. Restart Tomcat

For details see: [https://tomcat.apache.org/tomcat-8.0-doc/security-howto.html#Security_manager](url)

**Comment by rhuss** [comment]
Cool, thx for the tip.

1.3.4-SNAPSHOT has been pushed, please let me know whether it works for you (and reopen the issue if not)
