### ISSUE TITLE
Current Master branch cannot be built from command line

### ISSUE THREAD

**Issue by robstryker** [rhuss/jolokia#268]
The current master branch fails to build. The errors are all pom.xml related.

**Comment by robstryker** [comment]
Possible PR is here:  https://github.com/rhuss/jolokia/pull/269

**Comment by rhuss** [comment]
If it works with a fresh Maven repository for you, then it is pretty clear that your current ~/.m2/repository is broken. Could you try to move it away temporarily with `mvn ~/.m2/ ~/.m2.bak` and then retry a `mvn clean install` ?

It could be that simply a jar in your local repo is broken (which e.g. happens when you call maven on an hotel wlan with a paywall in front)

**Comment by rhuss** [comment]
@robstryker Any news on this ?

**Comment by olliebeef** [comment]
Sorry I've been a bit busy.  I'll wipe my repo and try again.  Thanks for all your help.

**Comment by robstryker** [comment]
Um... ignore olliebeef...  that was a test github user I made to test some redhat-developer stuff re: social logins.  Sorry about that.

**Comment by rhuss** [comment]
np at all ;-) thought first it was your alter ego ;-P

**Comment by robstryker** [comment]
So it seems to build fine after wiping my m2 folder and building my other projects... so there's no conflict or anything. Sorry for the delay; All seems well. Must have been something weird in the ol' m2.
