### ISSUE TITLE
ignore the org.apache.tomcat.util.net.SocketProperties?

### ISSUE THREAD

**Issue by zhaiyuyong** [rhuss/jolokia#300]
in the jconsole to see 8080 threadpool 
the SocketProperties show  Not available

if not ignore get Catalina:name="http-bio-7070",type=ThreadPool all attrs will fail
![image](https://cloud.githubusercontent.com/assets/4199724/21448819/9ed410e0-c921-11e6-9027-8e0dce5c5a96.png)

**Comment by rhuss** [comment]
Please try "?ignoreErrors=true" as query option to avoid bailing out in case on an error.

Jolokia is  a generic JMX-HTTP bridge which is agnostic to the JMX MBean it bridges. It does not and will never has any specific knowledge about the environment it is running in, except for the detectors. Beside this, hiding it here but returning the attribute name as result of a `search` or `list` operation is not consistent.

There are several ways for a client to avoid getting an error:

* Use specific attribute names in your read request instead of reading all attributes. You can give the read request even a list of attributes to read
* Use `ignoreErrors` query parameter to get all values, and the filter out the faulty ones.

It's a feature the Jolokia tries harder than jconsole to deserialize objects. This works most of the time, but not always and is not something Jolokia can influence, e.g. when an object throws an exception when calling a get-method. IMO its Tomcat's fault to expose complex objects via JMX which can not be used by an external client.

**Comment by zhaiyuyong** [comment]
OK  thx ,?ignoreErrors=true 
do work
