### ISSUE TITLE
can support like hadoop one url list all jmx item?

### ISSUE THREAD

**Issue by zhaiyuyong** [rhuss/jolokia#301]
like hadoop/hbase JMXJsonServlet.java can export all jmx item one http request and also query by type、name、path

so zabbix agent can dump all jmx item to tmp file one time

**Comment by zhaiyuyong** [comment]
![image](https://cloud.githubusercontent.com/assets/4199724/21451893/b55f95a2-c93d-11e6-885e-acd8c59ddc16.png)
![image](https://cloud.githubusercontent.com/assets/4199724/21451930/0b5d014c-c93e-11e6-8848-dd2253fdd027.png)

**Comment by rhuss** [comment]
You can do this, too, by using wildcard read patterns. See the reference manual for details. This is not necessarily recommended since it puts quite some load on the machine to monitor if there is a large number of MBeans (e.g. for Weblogic such a file can easily as large as 200 MB).

Please feel free to use also the forum (linke from the home page) as this is more appropriate for usage questions. GitHub issues are more for bug reports and feature requests. thanks.

**Comment by zhaiyuyong** [comment]
OK
