### ISSUE TITLE
Pull notifications returns null (2.0.0-M3)

### ISSUE THREAD

**Issue by sasha-alias** [rhuss/jolokia#306]
Hi, thanks for a great work on jolokia.
I'm trying to use jmx notifications feature as described at https://github.com/rhuss/jolokia/wiki/Notification-Protocol
I don't use jolokia client since I need that on server side, so I do http requests directly from nodejs.
Here are the steps I do:

1. register client to get `client_id` and `storage_name`. I get two values like:
```ini
client_id = "d45690d5-deb5-4fe8-910e-7b85fdad89fb"
storage_name = "jolokia:type=NotificationStore,agent=b4c966a-jvm"
```
2. subscribe to a 3d party MBean (`org.apache.cassandra.db:type=StorageService` in my case). I get a handle value which is usually `1`.

3. Start pulling notifications every few seconds by calling smth like:
```
http://host:port/jolokia/exec/jolokia:type=NotificationStore,agent=b4c966a-jvm/pull/d45690d5-deb5-4fe8-910e-7b85fdad89fb/1
```
I tried both POST and GET ways of executing it and get the following response:
```
{
  "request": {
    "mbean": "jolokia:agent=b4c966a-jvm,type=NotificationStore",
    "arguments": [
      "d45690d5-deb5-4fe8-910e-7b85fdad89fb",
      "1"
    ],
    "type": "exec",
    "operation": "pull"
  },
  "value": null,
  "status": 200,
  "timestamp": 1487263810
}
```

**Result**
The `value ` is always `null`. Even though if I subscribe in JConsole I see notifications are coming from that MBean.

Do you have any idea what I'm doing wrong? Or are there any restrictions I should know about? Or how can I troubleshoot it? A comprehensive example you can find here https://github.com/sasha-alias/jolokia-notification-example
If somebody could test it on verified environment it would be very helpful as well.

I use a jolokia build `jolokia-agent-jvm-2.0.0-M3-agent.jar`

Thank you

**Comment by rhuss** [comment]
Thanks a lot for trying out notifications ! Really happy because it seemed that nobody really cared about it (at least there was no much interest).

So lets try to get it fly :)

First of all, you probably already know the JavaScript code used for handling the notification stuff at https://github.com/rhuss/jolokia/blob/2.0/client/javascript/src/main/javascript/jolokia.js#L413 . Just wanted to be sure.

I suspect, the empty filter list is the culprit. The filter is evaluated [here](https://github.com/rhuss/jolokia/blob/807e5c7e4ab552fb64a4cc8a5dec0ece1a791c2c/server/core/src/main/java/org/jolokia/server/core/service/notification/ListenerRegistration.java#L106-L106) and as you can see, if the list is empty (but non-null) then a filter is returned which will never match.

Could you try without the empty filter list you set when adding a notification ? Then you get all notification send from this MBean. Simply omit the key.

Does this help ?

**Comment by sasha-alias** [comment]
Yeah, that was it!
Thanks a lot for a help!
Regarding notifications API I really hope you won't give it up. When dealing with asynchronous JMX API there is no choice really. I tried to find alternatives and found nothing beyond the java world. This just makes jolokia more feature complete solution I think. Looking forward for release.

Can I also ask about `notifications/add` parameters? There are `config` and `handback` params. What are the usecases for them?

**Comment by rhuss** [comment]
your are welcome ;-) Yes, I plan to release Jolokia 2.0 as soon as possible (but I keep saying this since ~ two years ;-).

The `handback` json / string that you provide during subscription is send back with every notification. You can use this to correlate your subscriptions on the client.

The `config` is currently not used but could be used by a backend ("pull" or "sse") for further configuration of a subscription. Not sure whether it will survive.

**Comment by sasha-alias** [comment]
Thanks a lot man!
I really appreciate the work you do and the speed you react with, that's just awesome!
Closing the issue.
