### ISSUE TITLE
DateUtil.fromISO8601(DateUtil.toISO8601(currentDate)) returns a different date

### ISSUE THREAD

**Issue by apupier** [rhuss/jolokia#329]
I was surprised that DateUtil.fromISO8601(DateUtil.toISO8601(currentDate) returns a different Date (for few milliseconds)

it looks alike a bug for me but i don't understand what is the wrong in the code exactly.

I updated a test to emphasize it: https://github.com/apupier/jolokia/tree/86-FailingDateRoundtripConversion

**Comment by Vest** [comment]
Hi @apupier, 

Oh, I think it is simple. It is because ISO 8601 in the current implementation doesn't have the milliseconds accuracy (in Wikipedia you should use this word instead of precision 😄 - [ISO 8601](https://en.wikipedia.org/wiki/ISO_8601)).

If you look at the source code ([DateUtil.java](https://github.com/rhuss/jolokia/blob/master/agent/core/src/main/java/org/jolokia/util/DateUtil.java#L91)), you will see the following date format: **"yyyy-MM-dd'T'HH:mm:ssZ"**.

You see? This is where the accuracy is lost. I think the fix should be obvious, but I do not know whether this date format is used somewhere, where this accuracy is not required.

_p.s. I do not know whether this project alive or not. Pull requests are not accepted for a long time._

**Comment by rhuss** [comment]
@Vest you are right, it looks like that velocity on Jolokia development has dropped quite a bit. Sorry for that, but I'm simply completely overloaded with tons of other stuff.

This does not mean that I'm not still committed to the project. If you look at the release history, there has always been new releases and support over the years.

That there are still 8 PRs dangling is a shame, but I try to get to is asap. Also, Jolokia is heavily used in RedHat products, so there will be support for Jolokia for some time to come.

Now to the issue: Actually I would prefer to cut off the millis to 0 in `DateUtil.fromISO8601()`, as this is probably the best fit. If a higher accuracy is required epoch time should be used. Does this make sense ?

**Comment by apupier** [comment]
ok so in fact the implementation was right, it's just that I miss the fact that ISO 8601 is not considering milliseconds
I updated the PR to include a test ensuring that it is the case

**Comment by Vest** [comment]
Maybe it can suppor milliseconds, if you change the format string. E.g. … mm:ss.sssZ

But I don't know whether it doesn't break the rest.

**Comment by rhuss** [comment]
I agree, that the format could be adapted, but if I understand https://en.wikipedia.org/wiki/ISO_8601 right, ISO-8601 only goes down to the second. 

Backwards compatibility is also an issue here, as you mention. So I would like to keep it this way, and if a higher accuracy is needed, we can refer to the epoch time.

@Vest @apupier is this ok for you ?

**Comment by Vest** [comment]
To be honest, I don't mind. I conetely agree with you, @rhuss

**Comment by apupier** [comment]
that's ok for me
