### ISSUE TITLE
Classname conflict with json-simple

### ISSUE THREAD

**Issue by akadoya** [rhuss/jolokia#350]
Because Jolokia  JSM agent contains a conflict class name with json-simple(org.json.simple.ItemList), it fails to start up an application like elassandra that uses jarHell for the code quality. (see https://github.com/strapdata/elassandra/issues/121)
Would it be possible to get rid of the duplicated class and just add a dependency to json-simple?

**Comment by rhuss** [comment]
@akadoya This is not really feasible for the JVM agent, as it has to be delivered as a self-contained, fat jar, containing all the dependencies. The JVM agent can't make any assumption where and how it is run, so this is required. Also, since it's running as an agent, all classes must be on the bootclasspath.

However, for your special setup, you might consider not to add the jolokia-jvm-agent.jar (the 'big' one with around 440k), but the contained jars individually.

These are:

* jolokia-jvm-1.3.7.jar for the JVM startup code. This must be added on the -javaagent path
* jolokia-core-1.3.7.jar on the bootclasspath
* json-simple also on the bootclasspath, this can be the jar you are using in your app.

I never tried this, but this setup could work.

Since this is not really a Jolokia issue (there's nothing I can do for your setup, sorry), I'm going to close this issue. Feel free to reopen it, if you think there is still something I could do from a Jolokia POV.

**Comment by akadoya** [comment]
Thank you @rhuss for the info, In fact, I tried your solution but it didn't work out due to the class: org.jolokia.backend.BackendManager..

**Comment by carlo4002** [comment]
Hello @akadoya ,
Did you find a solution for this ?

**Comment by rhuss** [comment]
See #398 for a proposed solution, i.e. repackaging all dependencies within the agent. I'm tight in time I can spend on this project, so in the meantime, if you feel fancy, I'm happy to help integrate a PR for adapting the build process.
