### ISSUE TITLE
Sometimes data is lost

### ISSUE THREAD

**Issue by zhaiyuyong** [rhuss/jolokia#381]
first time
![image](https://user-images.githubusercontent.com/4199724/39392815-71a9e206-4aef-11e8-8d24-8c2bfc3a27c0.png)
second time
![image](https://user-images.githubusercontent.com/4199724/39392825-862e1634-4aef-11e8-95c1-c4cb2240ad0c.png)

**Comment by rhuss** [comment]
This really is not a Jolokia issue but how your Hadoop MBean exposes information. As you can clearly see, there is no Jolokia error. All what Jolokia does is to expose the data which is there and which is different in your case. Remember, JMX allows dynamic changes the MBean data (e.g. for so called "Dyanmic MBeans"), so this situation that you describe can easily occur and is no error.

MY suggesstion is to contact the Hadoop community to find out more why this specific MBean exposes different types of data for different occasion.

I'm going to close this issue as there is nothing which Jolokia can help here. Feel free to reopen if you feel otherwise.
