### ISSUE TITLE
1.7.1 release missing gpg public keys for asc files

### ISSUE THREAD

**Issue by philjb** [rhuss/jolokia#482]
I'm pleased that ASC files are included in the 1.7.1 release from this September (2021). https://github.com/rhuss/jolokia/releases/tag/v1.7.1

However, I cannot validate the asc files against the other files with the public key pair to the signing key. Normally a KEYS file is also provided. 

I could be blind but I didn't see it. Would you supply it and/or include it in the release assets?

Existing assets:
![Screen Shot 2021-11-19 at 12 05 24 PM](https://user-images.githubusercontent.com/13472206/142685014-7061ae1b-25ca-44b7-8b0e-dc63cb46b18a.png)

**Comment by rhuss** [comment]
So you mean to add the public key for 8ADF74511D217D2835EAA59381D53EB87CDFBC34 as `KEYS` file ? Not sure if this enhances security because if GitHub is compromised the key could easily be forged along with the signatures, too.

Currently, the public key (it's my personal key) is available on the usual PGP keyservers.

Maybe it's better to provide a download option from the website for the public key or some other means ?

**Comment by philjb** [comment]
> Currently, the public key (it's my personal key) is available on the usual PGP keyservers.

This was the missing information for me. I can get your key that way fine.

> you mean to add the public key for 8ADF74511D217D2835EAA59381D53EB87CDFBC34 as KEYS file ? Not sure if this enhances security because if GitHub is compromised the key could easily be forged along with the signatures, too.

Yes - that was my suggestion. Apache does it this way with KEYS - you're not wrong about the double compromise. I keep a copy of the public signing key instead of fetching it each time. 

Really my ask was just to make it obvious where to get the public key that was used to sign artifacts. It wasn't clear to me just looking at the github assets page.

Appreciate your help here!

**Comment by rhuss** [comment]
@philjb Isn't it that when you do a `gpg --verify jolokia-1.7.1-bin.tar.gz.asc jolokia-1.7.1-bin.tar.gz` that it will show you with which key it was signed, so that you can fetch it from a keyserver ? True, you still would need to verify this (by eg. pinging one of the email addresses or calling me to get the fingerprint), but you have some context info (including a nice embedded picture ;-)

For the next release I will try to a KEYS file, just need to find out how to add it to the automation of the Maven release plugin.

**Comment by philjb** [comment]
> Isn't it that when you do a gpg --verify jolokia-1.7.1-bin.tar.gz.asc jolokia-1.7.1-bin.tar.gz that it will show you with which key it was signed, so that you can fetch it from a keyserver?

Yeah of course you're right about this. 😳 

Appreciate your responsiveness - feel free to close this whenever.
